ppaChannel = function(s){this.shortName = s;this.name = null;this.logo = null;this.review = null;this.listing = null;this.getChannel();};
ppaChannel.showError = function(e){alert(e);};
ppaChannel.prototype.getChannelAsync = function(ht) {var r = ppaGetMainNode(ht.responseXML);try{ht.channel.name = r.getElementsByTagName("name").item(0).firstChild.nodeValue;}catch(e){}try{ht.channel.logo = r.getElementsByTagName("logo").item(0).firstChild.nodeValue;}catch(e){}try{ht.channel.review = r.getElementsByTagName("review").item(0).firstChild.nodeValue;}catch(e){}try{ht.channel.listing = r.getElementsByTagName("prg");}catch(e){}};
ppaChannel.prototype.getChannel = function(){var sn        = escape(this.shortName).replace("+", "%2B");var _url      = SERVICES_PATH + "?action=channel_info&short_name=" + sn;var ht        = new HTTPRequest( );ht.channel    = this;ht.timeout    = 2000;ht.url        = _url;ht.onError    = ppaChannel.showError;ht.onSuccess  = ht.channel.getChannelAsync;ht.async      = false;ht.cache      = true;ht.process( );};
ppaChannel.prototype.getShortName = function(){return this.shortName;};
ppaChannel.prototype.getName = function(){return this.name;};
ppaChannel.prototype.getImage = function(){return "<img src=\"" + this.logo + "\" />";};
ppaChannel.prototype.getReview = function(){return this.review;};
ppaChannel.prototype.getListing = function(){var len = this.listing.length;var out = "<table id=\"ppa_chn_listing\">";var prg = this.listing.item(0);out += "<tr><td colspan=\"2\"><h1>Hoy en " + this.name + "</h1></td></tr>";out += "<tr><th>Estamos Presentando</th><th></th></tr>";out += "<tr><td class=\"col1_0\">" + prg.getAttribute("time") + "</td><td class=\"col2_0\">" + prg.firstChild.nodeValue + "</td></tr>";out += "<tr><th>A continuaci&oacute;n</th><th></th></tr>";for(var i=1; i<len; i++){prg = this.listing.item(i);var l = i%2;out += "<tr><td class=\"col1_" + l + "\">" + prg.getAttribute("time") + "</td><td class=\"col2_" + l + "\">" + prg.firstChild.nodeValue + "</td></tr>";}out += "</table>";return out;};
