GridApp.frm = null;GridApp.setGridPage = function(str){GridApp.gridPage = str;};
GridApp.resetSelect = function(id){var sel = document.getElementById(id);sel.selectedIndex = 0;};
GridApp.rechargeSelect = function(id){GridApp.category = document.getElementById("ppa_gender").value;var sel = document.getElementById(id);var fc = sel.parentNode;var ch = document.createElement("select");ch.appendChild(document.createElement("option"));ch.firstChild.appendChild(document.createTextNode("Cargando..."));fc.replaceChild(ch, sel);ch.id = id;if(id=="ppa_gender")	var _url = SERVICES_PATH + "?action=filters" + ((GridApp.header!=0)?("&header=" + GridApp.header):"");else	var _url = SERVICES_PATH + "?action=filters" + ((GridApp.category!=0)?("&category=" + GridApp.category):"") + ((GridApp.header!=0)?("&header=" + GridApp.header):"");var ht=new HTTPRequest();ht.timeout= 2000;ht.url= _url;ht.onError= showError;ht.async= false;ht.cache= false;ht.process( );var root_el = ppaGetMainNode(ht.responseXML);if(id=="ppa_gender")	var newsel = GridApp.createGenderSel(root_el.getElementsByTagName("categories").item(0));else	var newsel = GridApp.createChannelSel(root_el.getElementsByTagName("channels").item(0));fc.replaceChild(newsel, ch);};
GridApp.createGenderSel = function(xml){var sel  = document.createElement("select");sel.name = "gender";sel.id = "ppa_gender";if(GridApp.isLockGender) sel.disabled = true;sel.onchange = function(){GridApp.rechargeSelect("ppa_channel");};var fs   = xml.childNodes;var opt = document.createElement("option");opt.value = "0";opt.appendChild(document.createTextNode("Todos"));sel.appendChild(opt);for(var i=0;i<fs.length;i++){var opt = document.createElement("option");opt.value = fs[i].getAttribute("id");try{opt.appendChild(document.createTextNode(fs[i].firstChild.nodeValue));  sel.appendChild(opt);}catch(e){}}if(GridApp.category!="")sel.value = GridApp.category;return sel;};
GridApp.createCitySel = function(){var sel  = document.createElement("select");var slected;if(GridApp.isLockHeadend)	sel.disabled = true;sel.name = "city";sel.id = "ppa_city";sel.onchange = function(){GridApp.header=getIdFromCityName(this.value);GridApp.rechargeSelect("ppa_gender");GridApp.rechargeSelect("ppa_channel");};if(GridApp.headerName!="")for(var i in ppaCitiesId ){var opt = document.createElement("option");opt.value = ppaCitiesName[i];try{if(opt.value.match("function")) continue;}catch(e){};try{opt.appendChild(document.createTextNode(ppaCitiesName[i]));if(ppaCitiesName[i].toLowerCase() == GridApp.headerName){slected=opt;GridApp.header = ppaCitiesId[i];}sel.appendChild(opt);}catch(e){}}else for(var i in ppaCitiesId ){var opt = document.createElement("option");opt.value = ppaCitiesName[i];try{if(opt.value.match("function")) continue;}catch(e){};try{opt.appendChild(document.createTextNode(ppaCitiesName[i]));sel.appendChild(opt);}catch(e){}}if(GridApp.category!="")sel.value = GridApp.category;if(slected!=undefined)slected.selected = "true";return sel;};
GridApp.createCityField = function(){var div = document.createElement("div");div.className = "cities_fld";div.appendChild(GridApp.createCitySel());return div;};
GridApp.createChannelSel = function(xml){var sel  = document.createElement("select");sel.name = "channel";sel.id = "ppa_channel";if(GridApp.isLockChannel) sel.disabled = true;var fs   = xml.childNodes;var opt = document.createElement("option");opt.value = "0";opt.appendChild(document.createTextNode("Todos"));sel.appendChild(opt);if(GridApp.channel!="")for(var i=0; i<fs.length;i++){	opt = document.createElement("option");	opt.value = fs[i].getAttribute("id");	var chn = fs[i].firstChild.nodeValue;	opt.appendChild(document.createTextNode(chn));	if(chn == GridApp.channel||opt.value == GridApp.channel) opt.selected = "true";	sel.appendChild(opt);}else for(var i=0; i<fs.length; i++){opt = document.createElement("option");opt.value = fs[i].getAttribute("id");opt.appendChild(document.createTextNode(fs[i].firstChild.nodeValue));sel.appendChild(opt);}return sel;};
GridApp.createGenderField = function(xml){var div = document.createElement("div");var txt = document.createElement("p");txt.appendChild(document.createTextNode("Género"));div.appendChild(txt);div.appendChild(GridApp.createGenderSel(xml));return div;};
GridApp.createHeaderField = function(){var div = document.createElement("div");var txt = document.createElement("p");var sel = document.createElement("select");sel.id = "ppa_header";sel.onchange = function(){GridApp.rechargeSelect("ppa_channel");};var opt = null;txt.appendChild(document.createTextNode("Ciudad"));div.appendChild(txt);div.appendChild(sel);opt = document.createElement("option");opt.value = "65";opt.innerHTML = "Bogotá";sel.appendChild(opt);opt = document.createElement("option");opt.value = "95";opt.innerHTML = "Cali";sel.appendChild(opt);opt = document.createElement("option");opt.value = "96";opt.innerHTML = "Medellín";sel.appendChild(opt);opt = document.createElement("option");opt.value = "97";opt.innerHTML = "Pereira";sel.appendChild(opt);return div;};
GridApp.createChannelField = function(xml){var div = document.createElement("div");var txt = document.createElement("p");txt.appendChild(document.createTextNode("Canal"));div.appendChild(txt);div.appendChild(GridApp.createChannelSel(xml));return div;};
GridApp.showStartCal = function(){  startCal.showAtElement(document.getElementById("ppa_startDate"));};
GridApp.showEndCal = function(){  endCal.showAtElement(document.getElementById("ppa_endDate"));};
GridApp.onSelectDate = function(cal, date){cal.field.value = date;if(cal.dateClicked){cal.hide();}};
GridApp.closeHandler = function(cal){  cal.hide();  _dynarch_popupCalendar = null;};
GridApp.createCalendar = function(n,cal){cal.showTime = false;var i = document.createElement("input");i.id = n;i.name = n;cal.field = i;cal.create(document.getElementById("ppa_filterForm"));cal.setDateFormat("%Y-%m-%d %I:%M %p");return i;};
GridApp.createField = function(tit, cn){var div = document.createElement("div");if(cn)div.className=cn;var txt = document.createElement("p");txt.appendChild(document.createTextNode(tit));div.appendChild(txt);return div;};
GridApp.createSearchByField = function(){var div = GridApp.createField("Inicial");};
GridApp.createStartDateField = function(xml){var div = GridApp.createField("Fecha");var i = GridApp.createCalendar("ppa_startDate",startCal);i.onclick = GridApp.showStartCal;var d = new Date();var m = (d.getMonth() < 9 ? ("0" + (d.getMonth()+1)): d.getMonth()+1);var dt = (d.getDate() < 9 ? ("0" + d.getDate()): d.getDate());if( d.getHours() > 12 ){var h = d.getHours() - 12;var mer = "PM";}else{var h = d.getHours() == 0 ? 12 : d.getHours();var mer = "AM";}if(d.getMinutes() > 30 ) var mins = "30";else var mins = "00";if(GridApp.startDate!="") i.value = GridApp.startDate;else i.value = d.getFullYear() + "-" + m + "-" + dt + " " + h  + ":" + mins + " " + mer;i.readOnly = true;div.appendChild(i);var sd = new Date();startCal.setDate(sd);return div;};
GridApp.createEndDateField = function(xml){var div = GridApp.createField("Final");var i = GridApp.createCalendar("ppa_endDate",endCal);i.onclick = GridApp.showEndCal;if(GridApp.endDate!="") i.value = GridApp.endDate;else i.value = "Calendario";i.readOnly = true;div.appendChild(i);return div;};
GridApp.createInputField = function(tit, nam, val){var div = GridApp.createField(tit);div.className = "ppa_left";var i = document.createElement("input");i.name = nam; i.id = nam;if(val != "") i.value = val;div.appendChild(i);return div;};
GridApp.createSearchButton = function(){var div = document.createElement("div");div.className = "label";var b = document.createElement("input");b.className = "ppa_btnSearch";b.type = "submit";b.value = "Buscar";/*b.onclick = function(){try{ppaG.consultGrid(0);}catch(e){alert("La instancia principal no existe, revise la documentación! " + e)}};*/div.appendChild(b);return div;};
GridApp.createFilters = function(){
document.write('<form id="ppa_filterForm" name="ppa_filterForm" method="post" action="" onsubmit="ppaConsultGrid(0);return false"><div id="ppa_filterContainerTop"><\/div><\/form>');
var _url = SERVICES_PATH + "?action=filters" + ((GridApp.header!=0)?("&header=" + GridApp.header):"");
var ht = new HTTPRequest();
ht.timeout = 2000;
ht.url = _url;
ht.onError = showError;
ht.async = false;
ht.cache = false;
ht.process( );
var root_el = ppaGetMainNode(ht.responseXML);
var t = document.getElementById("ppa_filterContainerTop");
GridApp.frm = document.getElementById("ppa_filterForm");
var fc = document.createElement("div");
t.appendChild(fc);
fc.id = "ppa_filterContainer";
if(GridApp.isShowHeadend){document.getElementById("ppa_filterContainer").style.height="165px";
fc.appendChild(GridApp.createField("Ciudad","short_label"));
fc.appendChild(GridApp.createCityField());
}fc.appendChild(GridApp.createField("Buscar por","label"));
fc.appendChild(GridApp.createGenderField(root_el.getElementsByTagName("categories").item(0)));
fc.appendChild(GridApp.createChannelField(root_el.getElementsByTagName("channels").item(0)));
fc.appendChild(GridApp.createField("Fecha","label"));
fc.appendChild(GridApp.createStartDateField());
fc.appendChild(GridApp.createEndDateField());
fc.appendChild(GridApp.createInputField("Título", "ppa_title", GridApp.title));
fc.appendChild(GridApp.createInputField("Actor/Director", "ppa_actor", GridApp.actor));
fc.appendChild(GridApp.createSearchButton());
if(GridApp.category != "" ){GridApp.rechargeSelect("ppa_channel");}
};

var startCal = new Calendar(0, null, GridApp.onSelectDate, GridApp.closeHandler);var endCal = new Calendar(0, null, GridApp.onSelectDate, GridApp.closeHandler);GridApp.setGridPage(PPA_GRID_PAGE);