var WEB_GRID_LOCATION = "http://190.27.201.2/ppa/jsapps/inter/";
var PPA_GRID_PAGE = "grid.php";
var PPA_PRINT_GRID_PAGE = "print.php";
var SERVICES_PATH = "readfile.php";
//var ppaCitiesName   = ["- Seleccione una -","Acarigua","Anaco","Bachaquero","Barinas","Barquisimeto","Caracas","Carora","Chichiriviche","Ciudad Bolivar","Coro","Cumaná","El Tigre","Guanare","Los Teques","Maracaibo","Margarita","Maturín","Merida","Puerto Cabello","Puerto La Cruz","Punta de Mata","Punto Fijo","Region Central","Rubio","San Cristobal","San Felipe","San Fernando de Apure","Tinaco","Tinaquillo","Tucacas","Ureña","Valera","Vigia"];
//var ppaCitiesId = ["-1","48","55","76","53","26","46","7","72","51","81","91","54","92","57","45","82","79","50","93","62","84","49","44","94","61","52","74","73","75","106","83","58","80"];
var ppaCitiesName   = ["- Seleccione una -","Acarigua","Anaco","Bachaquero","Barcelona","Barinas","Barinitas","Barquisimeto","Bejuma","Cabimas","Cabudare","Cagua","Caja Seca","Caracas","Carora","Carrizal","Carvajal","Charallave","Chichiriviche","Ciudad Bolivar","Ciudad Ojeda","Cocorote","Cocorotico","Coro","Cúa","Cumaná","Cumarebo","Ejido","El Tigre","El Tigrito","El Vigía","Flor de Patria","Guacara","Guanare","Guarenas","Guatire","Güigüe","La Cejita","La Concepción","La Guaira","La Pradera","La Puerta","La Vela","Lagunillas","Lechería","Los Teques","Maracaibo","Maracay","Mariara","Maturín","Mérida","Miranda","Montalban","Morón","Naguanagua","Nirgua","Nueva Esparta","Palo Negro","Pam pam","Pampanito","Píritu","Porlamar","Puerto Cabello","Puerto La Cruz","Punta de Mata","Punto Fijo","Region Central","Rubio ","Salom","San Antonio","San Antonio del Táchira","San Carlos","San Cristobal","San Diego","San Felipe","San Fernando de Apure","San Francisco","San Joaquín","San Juan","San Mateo","Santa Cruz","Santa Rita","Tariba","Tinaco","Tinaquillo","Tocuyito","Tucacas","Turén","Turmero","Ureña","Valencia","Valera","Villa de Cura","Villa Flamingo","Yaritagua"];
var ppaCitiesId = ["-1","48","55","76","62","53","53","26","186","187","26","44","185","46","47","57","58","56","72","51","187","52","52","81","56","91","184","50","54","54","80","58","44","92","46","46","44","58","58","46","44","58","81","45","62","57","45","44","44","79","50","186","186","106","44","186","82","44","58","58","48","82","93","62","84","49","44","94","186","57","83","73","61","44","52","74","45","44","188","44","44","45","61","73","75","44","106","48","44","83","44","58","44","72","26"];
document.write("<script type='text/javascript' src='" + WEB_GRID_LOCATION + "js/LoadXML.js'></scr"+"ipt>");
function ppaImport(str){if(str == 'grid'){ if(typeof(GridApp)=="undefined") document.write("<script type='text/javascript' charset=\"ISO-8859-1\" src='" + WEB_GRID_LOCATION + "js/gridApp.js'></scr"+"ipt>");}else if(str == 'channel') { if(typeof(ppaChannel)=="undefined") document.write("<script type='text/javascript' src='" + WEB_GRID_LOCATION + "js/channelApp.js'></scr"+"ipt>");}
else if(str == 'filters'){if(typeof(Calendar)=="undefined") document.write("<script type='text/javascript' src='" + WEB_GRID_LOCATION + "js/calendar.js'></scr"+"ipt>");if(typeof(timeField)=="undefined") document.write("<script type='text/javascript' src='" + WEB_GRID_LOCATION + "js/timeField.js'></scr"+"ipt>");if(typeof(GridApp)=="undefined") document.write("<script type='text/javascript' charset=\"ISO-8859-1\" src='" + WEB_GRID_LOCATION + "js/gridApp.js'></scr"+"ipt>");gridAppIncludeCss(WEB_GRID_LOCATION + "css/filters.css");gridAppIncludeCss(WEB_GRID_LOCATION + "css/grid.css");document.write("<script type='text/javascript' charset=\"ISO-8859-1\" src='" + WEB_GRID_LOCATION + "js/filtersApp.js'></scr"+"ipt>"); } else if(str == 'highlights') { document.write("<script type='text/javascript' src='" + WEB_GRID_LOCATION + "js/highlightsApp.js'></scr"+"ipt>");}};
function gridAppIncludeJs(script_filename) { var html_doc = document.getElementsByTagName('head').item(0); var js = document.createElement('script'); js.setAttribute('language', 'javascript'); js.setAttribute('type', 'text/javascript'); js.setAttribute('src', script_filename); html_doc.appendChild(js); return false;};
function gridAppIncludeCss(css_filename) { var html_doc = document.getElementsByTagName('head').item(0); var js = document.createElement('link'); js.setAttribute('rel', 'stylesheet'); js.setAttribute('type', 'text/css'); js.setAttribute('media', 'all'); js.setAttribute('href', css_filename); html_doc.appendChild(js); return false;};
function ppaGetMainNode(node){mainNode = node.firstChild; if(mainNode.nodeType != 1) mainNode = mainNode.nextSibling; return mainNode;};
function showError( err ){ alert( err.statusText );};
function changeStatus( request ){ var yPos = document.body.scrollTop; var state_div = document.getElementById( "grid_container" ); switch ( request.readyState ) { case 1: state_div.innerHTML = "<div style=\"color:red;\">Error en el servidor</div>"; case 2: state_div.innerHTML = "<div style=\"color:red;\">Datos cargados</div>"; case 3: state_div.innerHTML = "<div style=\"color:red;\">Inicializando</div>"; case 4: if ( request.status == 200 || request.status == 304 ){ state_div.innerHTML = ""; } else { state_div.innerHTML = "<div>Cargando...</div>"; } break; default: state_div.innerHTML = "<div style=\"color:red;\">Cargando...</div>"; break; } };
function getWindowSize( ){ var w = 0, h = 0; if ( self.innerHeight ) /* all except Explorer*/ { w = self.innerWidth; h = self.innerHeight; } else if (document.documentElement && document.documentElement.clientHeight) { w = document.documentElement.clientWidth; h = document.documentElement.clientHeight;} else if (document.body) /* other Explorers*/ { w = document.body.clientWidth; h = document.body.clientHeight; } return { "w" : w, "h" : h };};
function getPageSize(){ var w = document.body.scrollWidth; var h = document.body.scrollHeight;  w = w ? w : 0;  h = h ? h : 0; return { "w" : w, "h" : h };};
function getPageScroll(){ var w = window.pageXOffset || document.body.scrollLeft || document.documentElement.scrollLeft;  var h = window.pageYOffset || document.body.scrollTop || document.documentElement.scrollTop;  w = w ? w : 0;  h = h ? h : 0;  return { "w" : w, "h" : h };};
function ppaConsultGrid(ofs){  if( typeof(GridApp.gridContainer) == "undefined" ) { GridApp.frm.action = GridApp.gridPage; GridApp.frm.submit(); } else GridApp.consultGrid(ofs); return false;};
function getIdFromCityName(str){for(var i in ppaCitiesName){if(str == ppaCitiesName[i]) return ppaCitiesId[i];}return 0;}
